---
title: "Penguin Flipper Lenghts ANOVA"
author: "Caio Vianna"
date: "11/7/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Load packages and read

Packaeges: tidyverse, car, onewaystests

```{r, include=FALSE}
library(tidyverse)
library(car)
library(onewaytests)

penguins <- read_csv ("penguins.csv")
```

Our question: Is there a significant difference in mean flipper lenghts for female Chinstrap, Gentoo, and Adelie penguins near Pamer Archpelago?

Maybe I can use one-way ANOVA...
-Independent observations
- Equal variance (levene's test)
- Normality (histogram/qqplots)

```{r}

counts <- with(penguins, table(Species,Sex))

penguins2 <- penguins %>% 
  mutate(
    common_name =
      case_when(
        Species == "Chinstrap penguin (Pygoscelis antarctica)" ~ "Chinstrap",
        Species == "Gentoo penguin (Pygoscelis papua)" ~ "Gentoo",
        Species == "Adelie Penguin (Pygoscelis adeliae)" ~ "Adelie"
      )
  ) %>% 
  select(-Species) %>% 
  filter(Sex == "FEMALE")

```

Explorattory

```{r}

hists <- ggplot(penguins2, aes(x = `Flipper Length (mm)`)) +
  geom_histogram(aes(fill = common_name)) +
  facet_wrap(~ common_name, scales = "free")
  
hists
  
qqs <- ggplot(penguins2, aes(sample = `Flipper Length (mm)` )) +
    geom_qq(aes(color = common_name)) +
    facet_wrap(~ common_name, scale = "free")

qqs



# Based on qq-plots and histograms, observations for each group appear normally distributed. Also, n> 30 for all groups, so means will be normally distributed by CLT

```


